# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bda99fa5d7ac0ec7e29a9a466b862c1f9722a68c49aaf060eaac6a8b6f737db4e46a503a930f6e5b99975479c5f9a30b8952185a93ac2919e3515c8abcedd51e

test:
  secret_key_base: 34267c940cc48a39aa4d1adedfca24fb716082c85d19bbb2e61516fb5aeba9c34b60577106bddbff9cdc311296450de1d63bec70e35ae1a677508726d1984a41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
